apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: w5irvp5rj-python
  janus-idp.io/tekton: w5irvp5rj-python
  backstage.io/kubernetes-id: w5irvp5rj-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w5irvp5rj-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
